spring:
  flyway:
    url: jdbc:mysql://localhost:3306/test_schema?tinyInt1isBit=false
    user: root
    password: pass
#    locations: classpath:/db/migration
  datasource:
    url: jdbc:mysql://localhost:3306/test_schema?tinyInt1isBit=false
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      database: MYSQL
      hibernate.ddl-auto: none
      show-sql: true
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect